title: Cucaracha alibianada
description: "Un eficiente y loco probrama de personal \U0001F6C2\U0001F39B️"
template:
  repo: cucaracha-alibianada-template
  name: cucaracha-alibianada
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
